# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a243a89865428ff52ffa5558e6f49e60eb31188377403e5f12693cd5a7c49419a3570228202af595dce5db862f596b491a7000de2e196e82a70c0cb998d61c4

test:
  secret_key_base: e7d964172f6d03df857dce30eae3ea9749ec737b718ac30e597a5b120412bba13cd85b699320a5f0769567580630817f15f315d150f1c9e2a79565a6a586a3c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
